# 차원축소 Assignment1

# ''' ? ''' 이 있는 부분을 채워주세요

참고하셔야 하는 함수들은 링크 달아드렸으니 들어가서 확인해보세요

무작정 빈칸 채우기가 아니라 꼭 차원축소 과정을 이해하시면서 과제를 진행하시면 좋겠습니다!!!

또 질문은 언제나 환영이니 과제하다가 궁금하신것 있으시면 자유롭게 물어보세요!!

# 1) PCA의 과정 차근차근 밟아보기

In [1]:
#기본 모듈 불러오기
import numpy as np
import numpy.linalg as lin
import matplotlib.pyplot as plt
import pandas as pd
import random

In [2]:
#설명변수 x1, x2, x3
x1 = [95, 91, 66, 94, 68, 63, 12, 73, 93, 51, 13, 70, 63, 63, 97, 56, 67, 96, 75, 6]
x2 = [56, 27, 25, 1, 9, 80, 92, 69, 6, 25, 83, 82, 54, 97, 66, 93, 76, 59, 94, 9]
x3 = [57, 34, 9, 79, 4, 77, 100, 42, 6, 96, 61, 66, 9, 25, 84, 46, 16, 63, 53, 30]

In [3]:
#   설명변수들을 하나의 행렬로
X = np.stack((x1,x2,x3),axis=0)

In [4]:
X = pd.DataFrame(X.T,columns=['x1','x2','x3'])

In [11]:
X

x1  x2   x3
0   95  56   57
1   91  27   34
2   66  25    9
3   94   1   79
4   68   9    4
5   63  80   77
6   12  92  100
7   73  69   42
8   93   6    6
9   51  25   96
10  13  83   61
11  70  82   66
12  63  54    9
13  63  97   25
14  97  66   84
15  56  93   46
16  67  76   16
17  96  59   63
18  75  94   53
19   6   9   30

### 1-1) 먼저 PCA를 시작하기 전 데이터 scaling!!!! 매우 중요합니다!

https://datascienceschool.net/03%20machine%20learning/02.01%20%EB%8D%B0%EC%9D%B4%ED%84%B0%20%EC%A0%84%EC%B2%98%EB%A6%AC%20%EA%B8%B0%EC%B4%88.html?highlight=%EC%A0%84%EC%B2%98%EB%A6%AC  를 참고하시면 도움이 될거에요

In [15]:
#scaling
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X_std=scaler.fit_transform(X)

In [16]:
features = X_std.T

In [17]:
features

array([[ 1.08573604,  0.93801686,  0.01477192,  1.04880625,  0.08863151,
        -0.09601747, -1.97943714,  0.2732805 ,  1.01187645, -0.53917504,
        -1.94250735,  0.16249111, -0.09601747, -0.09601747,  1.15959564,
        -0.35452606,  0.05170172,  1.12266584,  0.3471401 , -2.20101593],
       [ 0.02614175, -0.86575334, -0.92726334, -1.66538341, -1.41934339,
         0.76426183,  1.13332186,  0.42595679, -1.5116084 , -0.92726334,
         0.85652683,  0.82577183, -0.03536825,  1.28709688,  0.33369178,
         1.16407687,  0.64124181,  0.11840676,  1.19483187, -1.41934339],
       [ 0.30684189, -0.46445467, -1.30282049,  1.04460382, -1.47049366,
         0.97753455,  1.74883111, -0.1961776 , -1.40342439,  1.61469258,
         0.44098042,  0.60865359, -1.30282049, -0.76626636,  1.21227698,
        -0.06203907, -1.06807806,  0.50804969,  0.17270336, -0.5985932 ]])

### 1-2) 다음으로 공분산 행렬을 구합니다

https://docs.scipy.org/doc/numpy/reference/generated/numpy.cov.html 를 참고하시면 도움이 될거에요

In [25]:
X_cov=np.cov(X_std,y=None, rowvar=True, bias=False, ddof=None, fweights=None, aweights=None,  dtype=None)
X_cov

array([[ 0.30136812,  0.51938101,  0.31983688,  0.60665115,  0.46631287,
        -0.28131079, -1.00490241,  0.00487501,  0.76425019, -0.09214856,
        -0.82316154, -0.18521116,  0.0866557 , -0.25331108,  0.18011814,
        -0.36351505, -0.03871495,  0.27536682, -0.17487554, -0.30766479],
       [ 0.51938101,  0.89692565,  0.56606506,  0.99819708,  0.81435705,
        -0.49529771, -1.76608149,  0.0222245 ,  1.33043192, -0.21677206,
        -1.42639106, -0.31821091,  0.17908045, -0.39647123,  0.29473862,
        -0.60690901, -0.0298139 ,  0.47163291, -0.28242957, -0.55465732],
       [ 0.31983688,  0.56606506,  0.46075389,  0.25744073,  0.58234448,
        -0.38416892, -1.34597093,  0.1180625 ,  0.91982741, -0.57116275,
        -0.93686548, -0.18852564,  0.33482359,  0.0585546 ,  0.06310984,
        -0.22591325,  0.26033218,  0.26825464, -0.03080856, -0.52599029],
       [ 0.60665115,  0.99819708,  0.25744073,  2.45181233,  0.66014424,
        -0.29358439, -1.13271065, -0.34973264,  

### 1-3) 이제 고유값과 고유벡터를 구합니다

실습코드를 참고해주세요

In [27]:
eigenvalues, eigenvectors = np.linalg.eig(X_cov)

print(eigenvalues)
print(eigenvectors)

[ 0.00000000e+00+0.00000000e+00j  1.30792155e+01+0.00000000e+00j
  6.99629415e+00+0.00000000e+00j -5.32007542e-16+0.00000000e+00j
  3.47308529e-16+7.30281448e-17j  3.47308529e-16-7.30281448e-17j
 -3.11963288e-16+0.00000000e+00j -1.89737685e-16+1.52414328e-16j
 -1.89737685e-16-1.52414328e-16j -1.54108330e-16+0.00000000e+00j
  1.52323936e-16+0.00000000e+00j  3.08818772e-17+1.06182987e-16j
  3.08818772e-17-1.06182987e-16j  8.79238413e-17+5.63060550e-17j
  8.79238413e-17-5.63060550e-17j -8.07606678e-17+0.00000000e+00j
 -2.92894134e-17+0.00000000e+00j  8.70070214e-19+1.39468317e-17j
  8.70070214e-19-1.39468317e-17j -2.62992941e-18+0.00000000e+00j]
[[-9.88074549e-01+0.00000000e+00j  1.49247077e-01+0.00000000e+00j
  -3.78681305e-02+0.00000000e+00j  1.43963797e-01+0.00000000e+00j
  -7.92144419e-02-9.56579062e-03j -7.92144419e-02+9.56579062e-03j
   6.75745236e-02+0.00000000e+00j -1.33033618e-01+1.29131116e-01j
  -1.33033618e-01-1.29131116e-01j -3.85777775e-01+0.00000000e+00j
   3.60839448e-03+0

### 1-4) 고유값 분해: 고유값 분해의 곱으로 원래 공분산 행렬을 구해봅니다

https://docs.scipy.org/doc/numpy/reference/generated/numpy.dot.html 를 참고해주세요

A = 𝑃Λ𝑃`
이 식 기억나죠?

In [28]:
# 고유값을 대각행렬로 변환
lambda_matrix = np.diag(eigenvalues)

# 고유벡터 행렬로 변환
V = eigenvectors

# 원래 공분산 행렬 복원
reconstructed_X_cov = np.dot(np.dot(V, lambda_matrix), np.linalg.inv(V))

reconstructed_X_cov

array([[ 0.30136812-5.67915414e-33j,  0.51938101-7.84595938e-17j,
         0.31983688+3.42849371e-18j,  0.60665115-5.37837647e-17j,
         0.46631287+3.76284769e-16j, -0.28131079-1.34728481e-16j,
        -1.00490241-1.18737128e-16j,  0.00487501-1.10802148e-16j,
         0.76425019-8.38181231e-17j, -0.09214856+2.95640372e-17j,
        -0.82316154-6.57751398e-17j, -0.18521116-1.86859255e-16j,
         0.0866557 -9.80651528e-17j, -0.25331108+9.24394017e-17j,
         0.18011814-1.48914304e-16j, -0.36351505+2.21470418e-16j,
        -0.03871495-1.05603373e-16j,  0.27536682+1.38203779e-17j,
        -0.17487554+2.40013608e-16j, -0.30766479+5.06568844e-16j],
       [ 0.51938101-1.00074606e-32j,  0.89692565-1.37337429e-16j,
         0.56606506-2.36183169e-17j,  0.99819708-1.05735109e-16j,
         0.81435705+6.62244884e-16j, -0.49529771-2.29526044e-16j,
        -1.76608149-2.04195694e-16j,  0.0222245 -1.99811548e-16j,
         1.33043192-1.42945661e-16j, -0.21677206+3.84700431e-17j,
        -

### 1-5) 마지막으로 고유 벡터 축으로 값을 변환합니다


https://docs.scipy.org/doc/numpy/reference/generated/numpy.concatenate.html

In [33]:
def new_coordinates(X,eigenvectors):
  transformed_data=np.dot(X, eigenvectors)
  return transformed_data

transformed_data=new_coordinates(X_cov, eigenvectors)

# print(X_cov)
# print(eigenvectors)

# 2) PCA를 구현해보기

위의 과정을 하나의 함수로 표현해주세요!

1)에서 진행한 과정을 그대로 가져오면 됩니다..! ,

위에서 만든 함수(new_coordinate)도 가져오셔서 사용해도 좋아요!

+하지만 이 함수는 number이라는 인자를 받아서 pca에서 주성분 개수를 고려하도록 합니다!

고유값이 큰 축 순서로 정렬하는 과정 + 주성분 개수 number을 고려해야한다는 점을 유의해서 함수를 정의해주세요


In [34]:
eigenvectors

array([[-9.88074549e-01+0.00000000e+00j,  1.49247077e-01+0.00000000e+00j,
        -3.78681305e-02+0.00000000e+00j,  1.43963797e-01+0.00000000e+00j,
        -7.92144419e-02-9.56579062e-03j, -7.92144419e-02+9.56579062e-03j,
         6.75745236e-02+0.00000000e+00j, -1.33033618e-01+1.29131116e-01j,
        -1.33033618e-01-1.29131116e-01j, -3.85777775e-01+0.00000000e+00j,
         3.60839448e-03+0.00000000e+00j,  9.26519796e-02+1.26223363e-01j,
         9.26519796e-02-1.26223363e-01j, -6.83185886e-04+1.42516098e-01j,
        -6.83185886e-04-1.42516098e-01j,  6.07287013e-01+0.00000000e+00j,
         4.66688549e-01+0.00000000e+00j,  9.20819079e-01+0.00000000e+00j,
         9.20819079e-01-0.00000000e+00j,  9.82834683e-01+0.00000000e+00j],
       [ 4.10703752e-02+0.00000000e+00j,  2.59365660e-01+0.00000000e+00j,
        -4.94089855e-02+0.00000000e+00j,  3.14224831e-01+0.00000000e+00j,
         1.83375273e-01-7.58293406e-02j,  1.83375273e-01+7.58293406e-02j,
         6.33616966e-02+0.00000000e+0

In [ ]:
from sklearn.preprocessing import StandardScaler

def MYPCA(X,number):
  scaler = StandardScaler()

  X_std=scaler.fit_transform(X)

  X_cov=np.cov(X_std,y=None, rowvar=True, bias=False, ddof=None, fweights=None, aweights=None,  dtype=None)

  eigenvalues, eigenvectors = np.linalg.eig(X_cov)
  eigenvalues.sort()

  # 고유값을 대각행렬로 변환
  lambda_matrix = np.diag(eigenvalues)

  # 고유벡터 행렬로 변환
  V = eigenvectors

  # 원래 공분산 행렬 복원
  reconstructed_X_cov = np.dot(np.dot(V, lambda_matrix), np.linalg.inv(V))

  return reconstructed_X_cov

In [ ]:
MYPCA(X,3)

array([[ 0.31019368, -1.08215716, -0.07983642],
       [ 1.28092404, -0.43132556,  0.13533091],
       [ 1.38766381,  0.78428014, -0.12911446],
       [ 0.95087515, -1.15737142,  1.6495519 ],
       [ 1.84222365,  0.88189889,  0.11493111],
       [-1.12563709, -0.52680338,  0.06564012],
       [-2.71174416,  0.63290138,  0.71195473],
       [-0.03100441, -0.20059783, -0.50339479],
       [ 2.29618509,  0.07661447,  0.01087174],
       [-0.61585248, -0.205764  ,  1.82651199],
       [-1.73320252,  1.29971699,  0.09045178],
       [-0.82366049, -0.57164535, -0.27123176],
       [ 0.75619512,  0.73995175, -0.76710616],
       [-0.42344386,  0.26555394, -1.41533681],
       [-0.39581307, -1.64646874,  0.24104031],
       [-0.88581498,  0.15195119, -0.82271209],
       [ 0.24587691,  0.39139878, -1.15801831],
       [ 0.14741103, -1.22874561, -0.03110396],
       [-0.7161265 , -0.56781471, -0.86180345],
       [ 0.24475107,  2.39442622,  1.19337361]])

# 3) sklearn이랑 비교를 해보기

https://scikit-learn.org/stable/modules/generated/sklearn.decomposition.PCA.html 를 참고하시면 도움이 될거에요

In [35]:
from sklearn.decomposition import PCA
pca = PCA(n_components=2)
pca.fit(X)
print(pca.explained_variance_ratio_)
print(pca.singular_values_)

[0.49801396 0.26098404]
[163.3723068 118.2672923]


In [36]:
pca = PCA(n_components=2, svd_solver='full')
pca.fit(X)
print(pca.explained_variance_ratio_)
print(pca.singular_values_)
pca = PCA(n_components=1, svd_solver='arpack')
pca.fit(X)
print(pca.explained_variance_ratio_)
print(pca.singular_values_)


[0.49801396 0.26098404]
[163.3723068 118.2672923]
[0.49801396]
[163.3723068]


In [37]:
MYPCA(X,3)

NameError: ignored