# 과제 1

## Matrix 구현
1. Linear Regression에서 쓰이는 **정규방정식**을 행렬로 구현하고, sklearn 혹은 OLS 패키지를 통해 구한 **실제 값과 비교**해주세요.
2. LSE에서 쓰이는 Loss Function, **MSE**를 행렬로 구현해 출력해주세요.

### Data Load

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [3]:
import pandas as pd
data = pd.read_csv("/content/drive/MyDrive/tobigs/Data/regression_assign1.csv")

In [4]:
data.head()

y    x1    x2  x3   x4    x5
0  10  38.9  64.7   4  868  59.7
1  13  41.6  45.3  -4  957  61.4
2  11  39.7  74.1   8  786  61.0
3   7  37.3  48.0  19  984  67.5
4  10  39.5  51.9   6  700  57.2

In [5]:
data.shape     # y:(9,1), X:(9,5)

(9, 6)

In [6]:
X = data.drop(["y"], axis=1)
y = data.y

In [7]:
# Matrix 계산을 위해 X와 y를 numpy 형태로 바꾸어줍니다.
X = X.to_numpy()
y = y.to_numpy()

In [8]:
X

array([[  38.9,   64.7,    4. ,  868. ,   59.7],
       [  41.6,   45.3,   -4. ,  957. ,   61.4],
       [  39.7,   74.1,    8. ,  786. ,   61. ],
       [  37.3,   48. ,   19. ,  984. ,   67.5],
       [  39.5,   51.9,    6. ,  700. ,   57.2],
       [  37.4,   53.6,   -5. , 1037. ,   58.8],
       [  35.1,   71.4,    3. ,  986. ,   58.6],
       [  38.8,   58.3,    6. ,  819. ,   59.2],
       [  36.6,   52.6,  -19. ,  791. ,   54.4]])

In [9]:
y

array([10, 13, 11,  7, 10,  9,  9,  6,  5])

### 1. Normal Equation

In [10]:
import numpy as np
from numpy.linalg import inv

In [11]:
def estimate_beta(X, y):
    # add intercept
    designX = np.hstack([np.ones([X.shape[0], 1]), X])
    beta_hat = inv(designX.T.dot(designX)).dot(designX.T).dot(y)

    return beta_hat

In [12]:
beta_hat = estimate_beta(X, y)
beta_hat

array([-3.92447368e+01,  1.31232583e+00,  8.53744361e-02,  7.41849897e-02,
        1.50018573e-02, -3.42273652e-01])

#### 실제 값과 비교

In [13]:
from sklearn.linear_model import LinearRegression

In [33]:
model = LinearRegression()
model.fit(X, y)

pred = model.predict(X)

In [15]:
print(model.intercept_)   # intercept
print(model.coef_)   # 추정된 회귀계수 (intercept 제외)

-39.24473678135658
[ 1.31232583  0.08537444  0.07418499  0.01500186 -0.34227365]


### 2. MSE

In [43]:
def MSE(X, y, beta_hat):
    designX = np.hstack([np.ones([X.shape[0], 1]), X])
    y_pred = designX.dot(beta_hat)
    mse = np.mean((y - y_pred)**2)

    return mse

In [44]:
MSE(X, y, estimate_beta(X, y))

1.6155977229019145